"""STM32 消息、串口传输和协议实现。"""

from .messages import (
    Command,
    EventCode,
    MessageType,
    MotionFault,
    MotionFaultReason,
    Ops9Pose,
    Ops9Status,
    PoseCancelled,
    PoseGoal,
    PoseGoalState,
    PoseGoalStatus,
    PoseReached,
    PoseStarted,
    Response,
    ResponseStatus,
    TelemetryKind,
    SessionInfo,
    PoseSample,
    WheelSample,
    LinkStatsSample,
    decode_telemetry,
)
from .chassis import Stm32ChassisController
from .ops9 import Stm32Ops9Receiver, TimedOps9Pose
from .pose_goal import (
    PoseGoalBusy,
    PoseTransactionSnapshot,
    PoseTransactionState,
    Stm32PoseGoalController,
)
from .protocol import Frame, FrameDecoder, ProtocolError, crc16_ccitt
from .serial_link import CommandRejected, CommandTimeout, SerialLink, SerialLinkError

__all__ = [
    "Command",
    "CommandRejected",
    "CommandTimeout",
    "EventCode",
    "Frame",
    "FrameDecoder",
    "MessageType",
    "MotionFault",
    "MotionFaultReason",
    "Ops9Pose",
    "Ops9Status",
    "PoseCancelled",
    "PoseGoal",
    "PoseGoalBusy",
    "PoseGoalState",
    "PoseGoalStatus",
    "PoseReached",
    "PoseStarted",
    "PoseTransactionSnapshot",
    "PoseTransactionState",
    "ProtocolError",
    "Response",
    "ResponseStatus",
    "SerialLink",
    "SerialLinkError",
    "SessionInfo",
    "PoseSample",
    "WheelSample",
    "LinkStatsSample",
    "decode_telemetry",
    "Stm32ChassisController",
    "Stm32Ops9Receiver",
    "Stm32PoseGoalController",
    "TelemetryKind",
    "TimedOps9Pose",
    "crc16_ccitt",
]
