"""Generated by tools/generate_rpi_protocol.py; do not edit."""

from enum import IntEnum, IntFlag

HOST_PROTOCOL_VERSION = 4
VERSION = 2
MAX_PAYLOAD = 64

class Capability(IntFlag):
    QUERY_POSE = 0x01
    SPEED_LIMITS = 0x02
    BINARY_TELEMETRY = 0x04
    ASYNC_TX = 0x08
    SESSION_RECOVERY = 0x10
    ATOMIC_POSE_LIMITS = 0x20

class MessageType(IntEnum):
    COMMAND = 0x10
    RESPONSE = 0x11
    EVENT = 0x22
    TELEMETRY = 0x23
class Command(IntEnum):
    PING = 0x01
    STOP_ALL = 0x02
    SESSION_PROBE = 0x03
    SET_POSE_GOAL = 0x80
    CANCEL_POSE_GOAL = 0x81
    QUERY_POSE_GOAL = 0x82
    SET_SPEED_LIMITS = 0x83
    SET_POSE_GOAL_WITH_LIMITS = 0x84
class ResponseStatus(IntEnum):
    OK = 0x00
    UNKNOWN_COMMAND = 0x01
    INVALID_LENGTH = 0x02
    INVALID_ARGUMENT = 0x03
    BUSY = 0x04
    INTERNAL_ERROR = 0x05
class EventCode(IntEnum):
    POSE_STARTED = 0x10
    POSE_REACHED = 0x11
    POSE_CANCELLED = 0x12
    MOTION_FAULT = 0x13
class PoseState(IntEnum):
    IDLE = 0x00
    MOVING = 0x02
    REACHED = 0x03
    CANCELLED = 0x04
    FAULT = 0x05
class MotionFault(IntEnum):
    UNSPECIFIED = 0x00
    OPS9_LOST = 0x01
    HOST_LOST = 0x02
    CAN_FAULT = 0x03
    OUT_OF_BOUNDS = 0x04
    TIMEOUT = 0x05
    UART_FAULT = 0x06
    INTERNAL_ERROR = 0xFF
class TelemetryType(IntEnum):
    WHEEL = 0x01
    POSE = 0x02
    LINK_STATS = 0x03

REQUIRED_CAPABILITIES = (
    Capability.QUERY_POSE
    | Capability.SPEED_LIMITS
    | Capability.BINARY_TELEMETRY
    | Capability.ASYNC_TX
    | Capability.SESSION_RECOVERY
    | Capability.ATOMIC_POSE_LIMITS
)
