#!/usr/bin/env python3
"""Generate C/Python protocol constants from the checked-in JSON schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "protocol" / "rpi_binary_protocol.json"
C_PATH = ROOT / "Core" / "Inc" / "rpi_protocol_generated.h"
PY_PATH = ROOT / "pi-brain" / "app" / "binary_protocol_generated.py"
DOC_PATH = ROOT / "docs" / "binary-protocol-reference.generated.md"


def _load() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as stream:
        return json.load(stream)


def _c_enum(name: str, prefix: str, values: dict[str, int]) -> str:
    items = ",\n".join(
        f"    {prefix}_{key} = 0x{value:02X}" for key, value in values.items()
    )
    return f"typedef enum {{\n{items}\n}} {name};\n"


def render_c(schema: dict) -> str:
    capabilities = " | ".join(
        f"RPI_CAP_{key}" for key in schema["capabilities"]
    )
    sections = [
        "/* Generated by tools/generate_rpi_protocol.py; do not edit. */",
        "#ifndef RPI_PROTOCOL_GENERATED_H",
        "#define RPI_PROTOCOL_GENERATED_H",
        "",
        f"#define HOST_PROTOCOL_VERSION {schema['host_protocol_version']}U",
        f"#define RPI_PROTOCOL_VERSION {schema['wire_version']}U",
        f"#define RPI_PROTOCOL_MAX_PAYLOAD {schema['max_payload']}U",
        "",
        _c_enum("RpiCapability_t", "RPI_CAP", schema["capabilities"]).rstrip(),
        f"#define RPI_CAPABILITIES ((uint32_t)({capabilities}))",
        "",
        _c_enum("RpiMessageType", "RPI_MSG", schema["message_types"]).rstrip(),
        _c_enum("RpiCommand_t", "RPI_CMD", schema["commands"]).rstrip(),
        _c_enum("RpiResponseStatus_t", "RPI_STATUS", schema["response_status"]).rstrip(),
        _c_enum("RpiPoseEvent_t", "RPI_EVENT", schema["events"]).rstrip(),
        _c_enum("RpiPoseState_t", "RPI_POSE", schema["pose_states"]).rstrip(),
        _c_enum("RpiMotionFault_t", "RPI_FAULT", schema["motion_faults"]).rstrip(),
        _c_enum("RpiTelemetryType_t", "RPI_TELEM", schema["telemetry_types"]).rstrip(),
        "",
        "#endif",
        "",
    ]
    return "\n".join(sections)


def _py_enum(name: str, values: dict[str, int]) -> str:
    items = "\n".join(f"    {key} = 0x{value:02X}" for key, value in values.items())
    return f"class {name}(IntEnum):\n{items}\n"


def render_python(schema: dict) -> str:
    capabilities = "\n".join(
        f"    {key} = 0x{value:02X}" for key, value in schema["capabilities"].items()
    )
    sections = [
        '"""Generated by tools/generate_rpi_protocol.py; do not edit."""',
        "",
        "from enum import IntEnum, IntFlag",
        "",
        f"HOST_PROTOCOL_VERSION = {schema['host_protocol_version']}",
        f"VERSION = {schema['wire_version']}",
        f"MAX_PAYLOAD = {schema['max_payload']}",
        "",
        f"class Capability(IntFlag):\n{capabilities}\n",
        _py_enum("MessageType", schema["message_types"]).rstrip(),
        _py_enum("Command", schema["commands"]).rstrip(),
        _py_enum("ResponseStatus", schema["response_status"]).rstrip(),
        _py_enum("EventCode", schema["events"]).rstrip(),
        _py_enum("PoseState", schema["pose_states"]).rstrip(),
        _py_enum("MotionFault", schema["motion_faults"]).rstrip(),
        _py_enum("TelemetryType", schema["telemetry_types"]).rstrip(),
        "",
        "REQUIRED_CAPABILITIES = (",
        "    Capability.QUERY_POSE",
        "    | Capability.SPEED_LIMITS",
        "    | Capability.BINARY_TELEMETRY",
        "    | Capability.ASYNC_TX",
        "    | Capability.SESSION_RECOVERY",
        "    | Capability.ATOMIC_POSE_LIMITS",
        ")",
        "",
    ]
    return "\n".join(sections)


def render_markdown(schema: dict) -> str:
    lines = [
        "<!-- Generated by tools/generate_rpi_protocol.py; do not edit. -->",
        "# Binary protocol generated reference",
        "",
        f"- Host protocol version: `{schema['host_protocol_version']}`",
        f"- Binary wire version: `{schema['wire_version']}`",
        f"- Maximum payload: `{schema['max_payload']}` bytes",
        "",
    ]
    for title, key in (
        ("Capabilities", "capabilities"),
        ("Message types", "message_types"),
        ("Commands", "commands"),
        ("Response status", "response_status"),
        ("Events", "events"),
        ("Pose states", "pose_states"),
        ("Motion faults", "motion_faults"),
        ("Telemetry types", "telemetry_types"),
    ):
        lines.extend((f"## {title}", "", "| Name | Value |", "| --- | ---: |"))
        lines.extend(
            f"| `{name}` | `0x{value:02X}` |"
            for name, value in schema[key].items()
        )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = _load()
    outputs = {
        C_PATH: render_c(schema),
        PY_PATH: render_python(schema),
        DOC_PATH: render_markdown(schema),
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            parser.error("generated protocol files are stale: " + ", ".join(stale))
        return 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
